// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // All resources sidebar
  allSidebar: [
    {
      type: 'category',
      label: 'All',
      link: {
        type: 'generated-index',
        title: 'All Resources',
        description: 'Browse all Islamic resources in one place.',
      },
      items: [{ type: 'autogenerated', dirName: '.' }],
    },
  ],

  // Duas sidebar
  duasSidebar: [
    {
      type: 'category',
      label: 'Duas',
      link: {
        type: 'generated-index',
        title: 'Duas',
        description: 'All Duas in one place.',
      },
      items: [{ type: 'autogenerated', dirName: 'duas' }],
    },
  ],

  // Ziyarat sidebar
  ziyaratsSidebar: [
    {
      type: 'category',
      label: 'Ziyarat',
      link: {
        type: 'generated-index',
        title: 'Ziyarat',
        description: 'All Ziyarat resources in one place.',
      },
      items: [{ type: 'autogenerated', dirName: 'ziyarat' }],
    },
  ],
};

export default sidebars;
